version: '3.3'

services:

    graphdb:
        image: miguelfbrito/clav_graphdb
        build: ./graphdb
        networks:
            - network_backend

    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017
        networks:
            - network_backend
#        environment:
#            MONGO_INITDB_ROOT_USERNAME: 'username'
#            MONGO_INITDB_ROOT_PASSWORD: 'password'
        networks:
            - network_backend
    node:
        #build: ./server
        image: miguelfbrito/clav_node
        environment:
            MONGO_URI: 'mongodb://mongodb:27017/clav'
            GRAPHDB_URI: 'http://graphdb:7200'
            GRAPHDB_REPOSITORY: 'clav'
            FILE_STORE_SECRET_KEY: 'clav_api'
            PASSPORT_SECRET_KEY: 'clav_api'
            JWT_SECRET_KEY: 'clav_api'

        ports:
            - 8000:8000
        expose:
            - 8000
        networks:
            - network_backend
            - network_frontend
        depends_on:
            - mongodb
            - graphdb

        command: ["./wait-for-it.sh", "mongodb:27017", "--", "npm", "start"]

    client:
        image: miguelfbrito/clav_client
        #build: ./client
        ports:
            - 3000:3000
        environment:
            env_file: .env
            BACKEND: 'http://node:8000'
        volumes:
            - /usr/src/app/node_modules
        networks:
            - network_frontend
        depends_on:
            - node

networks:
    network_backend:
        driver: "bridge"
    network_frontend:
        driver: "bridge"
