version: '3.3'

services:

    graphdb:
        build: ./graphdb
        networks:
            - network_backend

    mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"
#        environment:
#            MONGO_INITDB_ROOT_USERNAME: 'username'
#            MONGO_INITDB_ROOT_PASSWORD: 'password'

    node:
        build: ./server
        environment:
            MONGO_URI: 'mongodb://mongodb:27017/clav'
            GRAPHDB_URI: 'http://graphdb:7200'
            GRAPHDB_REPOSITORY: 'clav'
            FILE_STORE_SECRET_KEY: 'clav_api'
            PASSPORT_SECRET_KEY: 'clav_api'
            JWT_SECRET_KEY: 'clav_api'

        ports:
            - 8000:8000
        networks:
            - network_backend
        depends_on:
            - mongodb
            - graphdb
        command: ["./wait-for-it.sh", "mongodb:27017", "--", "npm", "start"]

networks:
    network_backend:
        driver: "bridge"
